<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            'Superadmin',
            'Admin',
            'User',
            'Moderator',
            'Editor',
            'Viewer',
            'Contributor',
            'Guest',
            'Manager',
            'Supervisor',
            'Team Lead',
            'Project Manager',
            'Product Owner',
            'Scrum Master',
            'Developer',
            'Senior Developer',
            'Junior Developer',
            'Backend Engineer',
            'Frontend Engineer',
            'Full Stack Engineer',
            'DevOps Engineer',
            'QA Engineer',
            'Test Analyst',
            'Data Analyst',
            'Data Scientist',
            'Data Engineer',
            'Machine Learning Engineer',
            'Systems Administrator',
            'Network Administrator',
            'Database Administrator',
            'Security Analyst',
            'Security Officer',
            'IT Support',
            'Help Desk Agent',
            'UX Designer',
            'UI Designer',
            'Graphic Designer',
            'Content Writer',
            'Copywriter',
            'Technical Writer',
            'SEO Specialist',
            'Marketing Manager',
            'Marketing Coordinator',
            'Social Media Manager',
            'Brand Manager',
            'Sales Manager',
            'Sales Representative',
            'Account Executive',
            'Account Manager',
            'Customer Success Manager',
            'Customer Support Agent',
            'Billing Specialist',
            'Finance Manager',
            'Accountant',
            'Auditor',
            'Payroll Specialist',
            'HR Manager',
            'HR Coordinator',
            'Recruiter',
            'Talent Acquisition Specialist',
            'Training Coordinator',
            'Operations Manager',
            'Operations Coordinator',
            'Logistics Manager',
            'Warehouse Supervisor',
            'Inventory Manager',
            'Procurement Officer',
            'Vendor Manager',
            'Legal Counsel',
            'Compliance Officer',
            'Risk Manager',
            'Business Analyst',
            'Strategy Analyst',
            'Research Analyst',
            'Executive Assistant',
            'Office Manager',
            'Receptionist',
            'CEO',
            'CTO',
            'CFO',
            'COO',
            'CMO',
            'Director',
            'Vice President',
            'Board Member',
            'Consultant',
            'Freelancer',
            'Intern',
            'Trainee',
            'Volunteer',
            'Partner',
            'Stakeholder',
            'Client',
            'Vendor',
            'Reviewer',
            'Approver',
            'Publisher',
            'Subscriber',
            'Analyst',
            'Coordinator',
            'Specialist',
            'Administrator',
            'Observer',
            'Auditor Trainee',
        ];

        foreach ($roles as $role) {
            Role::firstOrCreate(['name' => $role]);
        }
    }
}